# baseURL = 'https://rahul0598.github.io/'
languageCode = 'en-us'
title = 'rahuldevajji'

# Theme to use
theme = "bettermotherfuckinghugowebsite"

# Pagination
paginate = 25
paginatePath = "page"

# enable last updated
# enableGitInfo = true

# Google analytics
# googleAnalytics = ""

# Copyright
copyright = "© 2023 — Rahul Devajji — All rights reserved."

# Highlighting

pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "emacs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"


# Menu
[menu]
# Header
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 1
  [[menu.main]]
    url = "/posts/"
    name = "posts"
    weight = 2
  [[menu.main]]
   url = "/tags/"
   name = "tags"
   weight = 3
  [[menu.main]]
   url = "/reading/"
   name = "reading"
   weight = 4
  [[menu.main]]
    url = "https://github.com/Rahul0598"
    name = "github"
    weight = 5


# Footer
 [[menu.footer]]
  url = "https://github.com/ihasdapie/bettermotherfuckinghugowebsite/"
  name = "Theme"
  weight = 1

 [[menu.footer]]
   url = "https://github.com/Rahul0598"
   name = "GitHub"
   weight = 1

# Links format
[permalinks]
  posts = "/posts/:slug/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"

[markup]
  [markup.goldmark.parser]
    block = true
    title = true


  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false




