services:
  build:
   image: klakegg/hugo:0.101.0-ext-alpine
   volumes:
     - ./config.toml:/src/config.toml
     - ./content:/src/content
     - ./resources:/src/resources
     - ./static:/src/static
     - ./themes:/src/themes

  server:
    image: klakegg/hugo:0.101.0-ext-alpine
    command: server --navigateToChanged
    volumes:
      - ./config.toml:/src/config.toml
      - ./content:/src/content
      - ./resources:/src/resources
      - ./static:/src/static
      - ./themes:/src/themes
    ports:
      - 1313:1313
  
  publish:
    image: klakegg/hugo:latest
    entrypoint: hugo-official
    environment:
      HUGO_ENV_ARG: "production"
    volumes:
      - .:/src

